from marshmallow import validates, fields, ValidationError

from api.models import Order
from app import ma


class OrderSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Order
        load_instance = True

    # Explicitly include user_id in the schema
    user_id = fields.Int(required=True)

    # If order_date is always generated by default, you can keep it as dump_only
    order_date = fields.DateTime(dump_only=True)
